Suppresses JS errors and updates assertions
* LW homepage returns JS errors:
```error
Unhandled promise rejection TypeError: undefined is not a constructor
(evaluating 'new(window.RTCPeerConnection||window.mozRTCPeerConnection
||window.webkitRTCPeerConnection)({iceServers:[]})')
   at https://alpha.library.nd.edu/static/js/main.8f087ce7.js:17

TypeError: undefined is not an object (evaluating 't.rendered')
    at https://alpha.library.nd.edu/static/js/main.8f087ce7.js:22 in wt
```
Supressing them in this release so the test cases can continue running
This issue is being tracked in https://jira.library.nd.edu/browse/LW-466

* Changes 'Research Guides' to 'Library Guides'